#pragma config(Motor,  port1,           lmogo,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           flDrive,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           blDrive,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           frDrive,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           brDrive,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           ldr4b,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rdr4b,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           manipulatorR,  tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           manipulatorL,  tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          rmogo,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

void pre_auton()
{

	bStopTasksBetweenModes = true;

}


task autonomous()
{

	AutonomousCodePlaceholderForTesting();
}


void tank(int left_speed  , int right_speed) {
	setMotor(flDrive , left_speed);
	setMotor(blDrive , left_speed);
	setMotor(frDrive , right_speed);
	setMotor(brDrive , right_speed);
}

task usercontrol()
{
	bLCDBacklight = true;
	string mainBattery, backupBattery;


	while (true)
	{
		clearLCDLine(0);
		clearLCDLine(1);

		//Robot Main Battery Level
		displayLCDString(0, 0, "Robot Main: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
		displayNextLCDString(mainBattery);

		//Robot Backup Battery Level
		displayLCDString(1, 0, "Robot Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');
		displayNextLCDString(backupBattery);

		//Tank from Code Boi
		tank(vexRT[Ch3], vexRT[Ch2]);

		//Lift from Code Boi
		if(vexRT[Btn6U] == 1)
		{
			motor[ldr4b] = -127;
			motor[rdr4b] = -127;
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[ldr4b] = 127;
			motor[rdr4b] = 127;
		}
		else
		{
			motor[ldr4b] = 0;
			motor[rdr4b] = 0;
		}


		//Mogo from Code Boi
		if(vexRT[Btn8L] == 1)
		{
			motor[lmogo] = 127;
			motor[rmogo] = 127;
		}
		else if (vexRT[Btn8R] == 1)
		{
			motor[lmogo] = -127;
			motor[rmogo] = -127;
		}
		else
		{
			motor[lmogo] = 0;
			motor[rmogo] = 0;
		}

		//Mani from BOI c0dE
		if(vexRT[Btn5U] == 1)
		{
			motor[manipulatorL] = -127;
			motor[manipulatorR] = 127;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[manipulatorL] = 127;
			motor[manipulatorR] = -127;
		}
		else
		{
			motor[manipulatorL] = 0;
			motor[manipulatorR] = 0;
		}



	}
}
